- hosts: frontends
  gather_facts: false
  tasks:
  - name: Smoke test
    uri:
     url: "http://{{ item }}"
     return_content: yes
    with_items:
      - "{{ inventory_hostname }}"
    register: webpage
    failed_when: "'Ansible has done its job' not in webpage.content"

#  - name: Fail if 'Ansible has done its job' is not in the page content
